"""V227 one-budget strict chronological news direction sample-weighting audit.

For every outer-train row, P_CORRECT_NEWS is generated by an expanding model
whose correctness labels are strictly earlier than the row by more than 35
minutes.  Unsupported early rows receive the neutral value 0.5.  The single
pre-registered transform ``0.5 + P_CORRECT_NEWS`` is applied to the training
sample weight of one fixed direction architecture and compared with the exact
same architecture without that multiplier and with immutable V69 no-op.

This is old-DEV diagnostic research, not independent confirmation.  It never
opens DEV_EXTENSION, Research Seal, Final Meta, role assignments, or state.
"""
from __future__ import annotations

import argparse
import ctypes
import gzip
import hashlib
import importlib
import json
import math
import os
import sys
from pathlib import Path
from typing import Any, Iterable, Sequence

for _name in (
    "OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
    "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS", "BLIS_NUM_THREADS",
):
    os.environ[_name] = "2"
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["NVIDIA_VISIBLE_DEVICES"] = "none"

import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, roc_auc_score
from sklearn.preprocessing import StandardScaler


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
OUT = HERE / "V227_DIRECTION_WEIGHTING"
V225_RUNNER = ROOT / "experiment_v225_high_confidence_news_discriminator.py"
V69 = ROOT / "output_V69" / "V69_FAIL_CLOSED_SELECTED_OOF.csv.gz"
DEV = ROOT / "data" / "dev_contract_v36_labeled.csv.gz"
EVENTS = ROOT / "data" / "dev_contract_v36_events.csv.gz"

EXPECTED = {
    "data/dev_contract_v36_labeled.csv.gz":
        "2152090f9c83f233f0abe0fcb4fdb4b1a50cee27da99b27865f8eda83c8d65e2",
    "data/dev_contract_v36_events.csv.gz":
        "6b49d4545f4d2cc95f76c5bfbc27e4f2836b23b2e3ff2488473d0fd1a7d1e748",
    "output_V69/V69_FAIL_CLOSED_SELECTED_OOF.csv.gz":
        "f532a01fba5633e8d549b04d45570bd087e7272a728a907b3633e2a9e71b5002",
    "experiment_v225_high_confidence_news_discriminator.py":
        "b1d137e135e5a251e7741a6533e800e9b2e592cf660a16e33c225d1a712a5a5e",
}
NEWS_SOURCES = ("US_NEWS", "KR_NEWS")
CANDIDATES = ("V69_NOOP", "ARCH_UNWEIGHTED", "PCORRECT_WEIGHTED")
EMBARGO = pd.Timedelta(minutes=35)
OUTER_BLOCKS = 6
PCORRECT_BLOCKS = 8
PCORRECT_MIN_HISTORY = 80
INNER_FRACTION = 0.70
HC_QUANTILE = 0.80
COST = 0.002
SEED = 22701
BOOTSTRAP_DRAWS = 1000
WEIGHT_TRANSFORM = "0.5 + P_CORRECT_NEWS"
MATERIAL_BUDGET = 1

FORBIDDEN_DIRECTION_FEATURES = {
    "y", "fwd_ret_30m", "correct_target", "signed_net", "material_target",
    "high_conf", "p_correct_news", "sample_multiplier", "outer_fold",
}

_CPU_IDS: tuple[int, ...] = (30, 31)
_V225: Any | None = None


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(4 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def json_clean(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(key): json_clean(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_clean(item) for item in value]
    if isinstance(value, np.ndarray):
        return json_clean(value.tolist())
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        number = float(value)
        return number if math.isfinite(number) else None
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    return value


def atomic_json(value: Any, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + f".tmp.{os.getpid()}")
    temporary.write_text(
        json.dumps(json_clean(value), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def atomic_csv_gz(frame: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = frame.to_csv(index=False, lineterminator="\n").encode("utf-8")
    temporary = path.with_name(path.name + f".tmp.{os.getpid()}")
    with temporary.open("wb") as handle:
        with gzip.GzipFile(filename="", mode="wb", fileobj=handle, mtime=0) as compressed:
            compressed.write(raw)
    temporary.replace(path)


def configure_runtime(cpu_ids: Sequence[int]) -> dict[str, Any]:
    global _CPU_IDS
    ids = tuple(dict.fromkeys(int(value) for value in cpu_ids))
    available = os.cpu_count() or 1
    require(ids and all(0 <= value < available for value in ids),
            f"V227_CPU_IDS_UNAVAILABLE:{ids}:logical={available}")
    for name in (
        "OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
        "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS", "BLIS_NUM_THREADS",
    ):
        os.environ[name] = "2"
    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
    os.environ["NVIDIA_VISIBLE_DEVICES"] = "none"
    if sys.platform == "win32":
        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
        kernel32.GetCurrentProcess.restype = ctypes.c_void_p
        kernel32.SetProcessAffinityMask.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
        kernel32.SetProcessAffinityMask.restype = ctypes.c_int
        mask = sum(1 << value for value in ids)
        ok = kernel32.SetProcessAffinityMask(
            kernel32.GetCurrentProcess(), ctypes.c_size_t(mask)
        )
        if not ok:
            raise OSError(ctypes.get_last_error(), "V227 affinity failed")
    elif hasattr(os, "sched_setaffinity"):
        os.sched_setaffinity(0, set(ids))
    _CPU_IDS = ids
    return {
        "cpu_ids": list(ids), "thread_count": 2, "gpu_hidden": True,
        "cuda_visible_devices": os.environ["CUDA_VISIBLE_DEVICES"],
    }


def get_v225() -> Any:
    """Import the read-only feature preparation module, then restore V227 limits."""
    global _V225
    if _V225 is None:
        if str(ROOT) not in sys.path:
            sys.path.insert(0, str(ROOT))
        _V225 = importlib.import_module("experiment_v225_high_confidence_news_discriminator")
        # V225 imports the repository-wide full-machine runtime policy.  V227 is
        # intentionally bounded, so restore its declared limits immediately.
        configure_runtime(_CPU_IDS)
    return _V225


def verify_authority() -> dict[str, Any]:
    paths = {
        "data/dev_contract_v36_labeled.csv.gz": DEV,
        "data/dev_contract_v36_events.csv.gz": EVENTS,
        "output_V69/V69_FAIL_CLOSED_SELECTED_OOF.csv.gz": V69,
        "experiment_v225_high_confidence_news_discriminator.py": V225_RUNNER,
    }
    actual = {}
    for name, path in paths.items():
        require(path.is_file(), f"V227_AUTHORIZED_INPUT_MISSING:{name}")
        actual[name] = sha256(path)
        require(actual[name] == EXPECTED[name], f"V227_AUTHORITY_HASH_FAIL:{name}")
    return {
        "sha256": actual,
        "labels": "immutable V36 DEV only",
        "direction_baseline": "immutable V69 outer-OOF no-op",
        "feature_preparation_code": "hash-pinned V225 runner, read-only",
        "dev_extension_loaded": False,
        "research_seal_loaded": False,
        "final_meta_loaded": False,
        "role_assignment_loaded": False,
        "state_loaded_or_modified": False,
    }


def bool_values(series: pd.Series) -> np.ndarray:
    return series.map(
        lambda value: value if isinstance(value, (bool, np.bool_))
        else str(value).strip().lower() in {"true", "1", "yes"}
    ).to_numpy(bool)


def load_news() -> pd.DataFrame:
    frame = get_v225().load_frame().copy()
    require(set(frame.source_family.unique()) == set(NEWS_SOURCES), "V227_SOURCE_FAIL")
    require(frame.event_id.is_unique, "V227_EVENT_ID_DUPLICATE")
    require(frame.timestamp_quality.fillna("").astype(str).str.upper().eq("EXACT").all(),
            "V227_NONEXACT_TIMESTAMP")
    frame["event_time_utc"] = pd.to_datetime(frame.event_time_utc, utc=True)
    frame["v69_high_conf"] = bool_values(frame.high_conf)
    return frame.sort_values(
        ["source_family", "event_time_utc", "event_id"], kind="mergesort"
    ).reset_index(drop=True)


def local_cluster_weight(frame: pd.DataFrame) -> np.ndarray:
    sizes = frame.groupby("text_cluster_id").event_id.transform("size").clip(lower=1)
    return 1.0 / sizes.to_numpy(float)


def pcorrect_multiplier(probability: Iterable[float]) -> np.ndarray:
    values = np.asarray(list(probability), dtype=float)
    require(np.isfinite(values).all(), "V227_NONFINITE_PCORRECT")
    require(((values >= 0.0) & (values <= 1.0)).all(), "V227_PCORRECT_RANGE")
    multiplier = 0.5 + values
    require(((multiplier >= 0.5) & (multiplier <= 1.5)).all(),
            "V227_WEIGHT_TRANSFORM_RANGE")
    return multiplier


def outer_folds(frame: pd.DataFrame) -> list[tuple[pd.DataFrame, pd.DataFrame, int, dict[str, Any]]]:
    ordered = frame.sort_values(["event_time_utc", "event_id"], kind="mergesort").reset_index(drop=True)
    blocks = np.array_split(np.arange(len(ordered)), OUTER_BLOCKS)
    output = []
    for fold in range(1, OUTER_BLOCKS):
        valid = ordered.iloc[blocks[fold]].copy()
        valid_start = pd.Timestamp(valid.event_time_utc.min())
        train = ordered[ordered.event_time_utc < valid_start - EMBARGO].copy()
        before_purge = len(train)
        valid_clusters = set(valid.text_cluster_id)
        train = train[~train.text_cluster_id.isin(valid_clusters)].copy()
        require(len(train) >= 120 and len(valid) >= 100 and train.y.nunique() == 2,
                f"V227_OUTER_SUPPORT_FAIL:{fold}")
        train_end = pd.Timestamp(train.event_time_utc.max())
        overlap = len(set(train.text_cluster_id) & valid_clusters)
        require(train_end < valid_start - EMBARGO and overlap == 0,
                f"V227_OUTER_LEAKAGE:{fold}")
        audit = {
            "outer_fold": fold, "train_n": len(train), "valid_n": len(valid),
            "valid_start": valid_start, "train_end": train_end,
            "embargo_minutes": 35.0,
            "text_cluster_purge_n": before_purge - len(train),
            "text_cluster_overlap_n": overlap,
        }
        output.append((train.reset_index(drop=True), valid.reset_index(drop=True), fold, audit))
    return output


def inner_split(train: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    ordered = train.sort_values(["event_time_utc", "event_id"], kind="mergesort").reset_index(drop=True)
    split = max(90, int(INNER_FRACTION * len(ordered)))
    valid = ordered.iloc[split:].copy()
    valid_start = pd.Timestamp(valid.event_time_utc.min())
    base = ordered[ordered.event_time_utc < valid_start - EMBARGO].copy()
    before = len(base)
    base = base[~base.text_cluster_id.isin(set(valid.text_cluster_id))].copy()
    overlap = len(set(base.text_cluster_id) & set(valid.text_cluster_id))
    require(len(base) >= 70 and len(valid) >= 30 and base.y.nunique() == 2,
            "V227_INNER_SUPPORT_FAIL")
    require(pd.Timestamp(base.event_time_utc.max()) < valid_start - EMBARGO and overlap == 0,
            "V227_INNER_LEAKAGE")
    return base.reset_index(drop=True), valid.reset_index(drop=True), {
        "inner_train_n": len(base), "inner_valid_n": len(valid),
        "inner_train_end": pd.Timestamp(base.event_time_utc.max()),
        "inner_valid_start": valid_start, "inner_embargo_minutes": 35.0,
        "inner_text_cluster_purge_n": before - len(base),
        "inner_text_cluster_overlap_n": overlap,
    }


def base_features(frame: pd.DataFrame) -> pd.DataFrame:
    output = get_v225().base_features(frame, "full").copy()
    forbidden = sorted(set(output.columns) & FORBIDDEN_DIRECTION_FEATURES)
    require(not forbidden, f"V227_FORBIDDEN_MODEL_FEATURE:{forbidden}")
    return output


def matrices(
    train: pd.DataFrame, target: pd.DataFrame, include_text: bool,
) -> tuple[Any, Any, dict[str, Any]]:
    x_train = base_features(train)
    x_target = base_features(target)
    require(list(x_train.columns) == list(x_target.columns), "V227_FEATURE_SCHEMA_DRIFT")
    imputer = SimpleImputer(strategy="median", add_indicator=True, keep_empty_features=True)
    scaler = StandardScaler()
    train_numeric = scaler.fit_transform(imputer.fit_transform(x_train))
    target_numeric = scaler.transform(imputer.transform(x_target))
    text_features = 0
    if include_text:
        vectorizer = TfidfVectorizer(
            lowercase=True, strip_accents="unicode", ngram_range=(1, 2), min_df=3,
            max_df=0.995, max_features=24000, sublinear_tf=True, dtype=np.float32,
        )
        train_text = vectorizer.fit_transform(train.news_text)
        target_text = vectorizer.transform(target.news_text)
        text_features = train_text.shape[1]
        train_matrix = sparse.hstack(
            [sparse.csr_matrix(train_numeric), train_text], format="csr"
        )
        target_matrix = sparse.hstack(
            [sparse.csr_matrix(target_numeric), target_text], format="csr"
        )
    else:
        train_matrix, target_matrix = train_numeric, target_numeric
    return train_matrix, target_matrix, {
        "raw_structured_feature_n": len(x_train.columns),
        "transformed_numeric_feature_n": int(train_numeric.shape[1]),
        "text_feature_n": int(text_features),
        "total_feature_n": int(train_matrix.shape[1]),
        "raw_text_included": bool(include_text),
        "forbidden_feature_overlap": [],
    }


def logistic(seed: int) -> LogisticRegression:
    return LogisticRegression(
        C=0.25, solver="liblinear", class_weight="balanced", max_iter=1000,
        random_state=seed,
    )


def fit_pcorrect(
    history: pd.DataFrame, target: pd.DataFrame, seed: int,
) -> tuple[np.ndarray, dict[str, Any]]:
    train_matrix, target_matrix, feature_audit = matrices(history, target, include_text=False)
    model = logistic(seed)
    model.fit(
        train_matrix, history.correct_target.to_numpy(int),
        sample_weight=local_cluster_weight(history),
    )
    prediction = np.clip(model.predict_proba(target_matrix)[:, 1], 1e-6, 1.0 - 1e-6)
    return prediction, feature_audit


def expanding_pcorrect(
    outer_train: pd.DataFrame,
    outer_fold: int,
    source_family: str,
    blocks: int = PCORRECT_BLOCKS,
    min_history: int = PCORRECT_MIN_HISTORY,
) -> tuple[pd.DataFrame, pd.DataFrame, list[dict[str, Any]]]:
    """Past-only correctness cross-fit for every outer-train row."""
    ordered = outer_train.sort_values(
        ["event_time_utc", "event_id"], kind="mergesort"
    ).reset_index(drop=True)
    ordered["p_correct_news_train"] = 0.5
    ordered["p_correct_supported"] = False
    row_evidence = []
    block_audits = []
    for block_number, positions in enumerate(np.array_split(np.arange(len(ordered)), blocks)):
        if not len(positions):
            continue
        target = ordered.iloc[positions].copy()
        target_start = pd.Timestamp(target.event_time_utc.min())
        history = ordered[ordered.event_time_utc < target_start - EMBARGO].copy()
        before_purge = len(history)
        target_clusters = set(target.text_cluster_id)
        history = history[~history.text_cluster_id.isin(target_clusters)].copy()
        overlap = len(set(history.text_cluster_id) & target_clusters)
        event_overlap = len(set(history.event_id) & set(target.event_id))
        supported = (
            len(history) >= min_history
            and history.correct_target.nunique() == 2
        )
        feature_audit: dict[str, Any] = {
            "raw_structured_feature_n": 0, "transformed_numeric_feature_n": 0,
            "text_feature_n": 0, "total_feature_n": 0,
            "raw_text_included": False, "forbidden_feature_overlap": [],
        }
        if supported:
            history_end = pd.Timestamp(history.event_time_utc.max())
            require(history_end < target_start - EMBARGO, "V227_PCORRECT_TIME_LEAKAGE")
            require(overlap == 0 and event_overlap == 0, "V227_PCORRECT_ID_LEAKAGE")
            probability, feature_audit = fit_pcorrect(
                history, target, SEED + outer_fold * 100 + block_number
            )
            ordered.loc[positions, "p_correct_news_train"] = probability
            ordered.loc[positions, "p_correct_supported"] = True
            gap_minutes: float | None = (
                target_start - history_end
            ).total_seconds() / 60.0
        else:
            history_end = (
                pd.Timestamp(history.event_time_utc.max()) if len(history) else None
            )
            gap_minutes = (
                (target_start - history_end).total_seconds() / 60.0
                if history_end is not None else None
            )
        require(overlap == 0 and event_overlap == 0, "V227_PCORRECT_PURGE_FAIL")
        block_audit = {
            "source_family": source_family, "outer_fold": outer_fold,
            "pcorrect_block": block_number, "target_n": len(target),
            "target_start": target_start, "target_end": pd.Timestamp(target.event_time_utc.max()),
            "history_n": len(history), "history_end": history_end,
            "minimum_history_gap_minutes": gap_minutes,
            "text_cluster_purge_n": before_purge - len(history),
            "text_cluster_overlap_n": overlap, "event_overlap_n": event_overlap,
            "supported": supported, "unsupported_policy": "NEUTRAL_0.5",
            "same_row_correctness_used": False,
            "strict_history_predicate": "history_time < target_block_start - 35m",
            **feature_audit,
        }
        block_audits.append(block_audit)
        for position in positions:
            row = ordered.iloc[position]
            row_evidence.append({
                "source_family": source_family, "outer_fold": outer_fold,
                "event_id": row.event_id, "event_time_utc": row.event_time_utc,
                "pcorrect_block": block_number,
                "p_correct_news_train": float(ordered.at[position, "p_correct_news_train"]),
                "p_correct_supported": bool(ordered.at[position, "p_correct_supported"]),
                "sample_multiplier": float(
                    pcorrect_multiplier([ordered.at[position, "p_correct_news_train"]])[0]
                ),
                "history_n": len(history), "history_end": history_end,
                "minimum_history_gap_minutes": gap_minutes,
                "correctness_model_fit_contains_event": False,
                "text_cluster_overlap_n": overlap,
            })
    evidence = pd.DataFrame(row_evidence)
    require(len(evidence) == len(ordered) and evidence.event_id.is_unique,
            "V227_PCORRECT_ROW_COVERAGE_FAIL")
    require(not evidence.correctness_model_fit_contains_event.any(),
            "V227_SAME_ROW_CORRECTNESS")
    require(evidence.p_correct_news_train.between(0.0, 1.0).all(),
            "V227_PCORRECT_OUTPUT_RANGE")
    return ordered, evidence, block_audits


def fit_direction_pair(
    train: pd.DataFrame, target: pd.DataFrame, seed: int,
) -> tuple[dict[str, np.ndarray], dict[str, Any]]:
    train_matrix, target_matrix, feature_audit = matrices(train, target, include_text=True)
    cluster = local_cluster_weight(train)
    multiplier = pcorrect_multiplier(train.p_correct_news_train.to_numpy(float))
    weights = {
        "ARCH_UNWEIGHTED": cluster,
        "PCORRECT_WEIGHTED": cluster * multiplier,
    }
    output = {}
    for candidate, sample_weight in weights.items():
        model = logistic(seed)
        model.fit(train_matrix, train.y.to_numpy(int), sample_weight=sample_weight)
        output[candidate] = np.clip(
            model.predict_proba(target_matrix)[:, 1], 1e-6, 1.0 - 1e-6
        )
    audit = {
        **feature_audit,
        "architecture": "FULL_STRUCTURED_TEXT_L2_LOGISTIC_C_0.25_BALANCED",
        "same_feature_matrix_both_candidates": True,
        "unweighted_definition": "local text-cluster duplicate weight only",
        "weighted_definition": f"local text-cluster duplicate weight * ({WEIGHT_TRANSFORM})",
        "p_correct_supported_n": int(train.p_correct_supported.sum()),
        "p_correct_neutral_n": int((~train.p_correct_supported).sum()),
        "p_correct_mean": float(train.p_correct_news_train.mean()),
        "sample_multiplier_mean": float(multiplier.mean()),
        "sample_multiplier_min": float(multiplier.min()),
        "sample_multiplier_max": float(multiplier.max()),
    }
    return output, audit


def candidate_rows(
    valid: pd.DataFrame,
    probability: np.ndarray,
    high_conf: np.ndarray,
    candidate: str,
    outer_fold: int,
    threshold: float | None,
) -> pd.DataFrame:
    prediction = probability >= 0.5
    correct = prediction == valid.y.to_numpy(int).astype(bool)
    signed_net = np.where(prediction, 1.0, -1.0) * valid.fwd_ret_30m.to_numpy(float) - COST
    output = valid[[
        "event_id", "event_time_utc", "ticker", "source_family", "fold", "y",
        "fwd_ret_30m", "text_cluster_id",
    ]].copy()
    output["candidate"] = candidate
    output["outer_fold"] = outer_fold
    output["prob_direction"] = probability
    output["direction_prediction"] = prediction
    output["direction_correct"] = correct.astype(int)
    output["signed_net"] = signed_net
    output["high_conf"] = high_conf
    output["hc_threshold"] = np.nan if threshold is None else float(threshold)
    output["outer_labels_used_for_threshold_or_selection"] = False
    return output


def run_source(
    frame: pd.DataFrame,
) -> tuple[pd.DataFrame, list[dict[str, Any]], pd.DataFrame, list[dict[str, Any]]]:
    source_family = str(frame.source_family.iloc[0])
    predictions = []
    fold_audits = []
    pcorrect_rows = []
    pcorrect_blocks = []
    for train_raw, valid, outer_fold, outer_audit in outer_folds(frame):
        train, p_rows, p_blocks = expanding_pcorrect(
            train_raw, outer_fold, source_family
        )
        pcorrect_rows.append(p_rows)
        pcorrect_blocks.extend(p_blocks)
        inner_train, inner_valid, inner_audit = inner_split(train)
        inner_probability, inner_model_audit = fit_direction_pair(
            inner_train, inner_valid, SEED + outer_fold * 1000
        )
        thresholds = {
            candidate: float(np.quantile(np.abs(probability - 0.5), HC_QUANTILE))
            for candidate, probability in inner_probability.items()
        }
        outer_probability, outer_model_audit = fit_direction_pair(
            train, valid, SEED + outer_fold * 1000 + 1
        )
        for candidate in ("ARCH_UNWEIGHTED", "PCORRECT_WEIGHTED"):
            margin = np.abs(outer_probability[candidate] - 0.5)
            high = margin >= thresholds[candidate]
            predictions.append(candidate_rows(
                valid, outer_probability[candidate], high, candidate,
                outer_fold, thresholds[candidate],
            ))
        v69_probability = valid.prob.to_numpy(float)
        predictions.append(candidate_rows(
            valid, v69_probability, valid.v69_high_conf.to_numpy(bool),
            "V69_NOOP", outer_fold, None,
        ))
        require(np.array_equal(v69_probability, valid.prob.to_numpy(float)),
                "V227_V69_PROB_CHANGED")
        require(np.array_equal(
            predictions[-1].high_conf.to_numpy(bool), valid.v69_high_conf.to_numpy(bool)
        ), "V227_V69_HIGH_CONF_CHANGED")
        fold_audits.append({
            "source_family": source_family, "outer_fold": outer_fold,
            **outer_audit, **inner_audit,
            "hc_gate_rule": "fixed q80 of absolute direction margin on inner-past predictions",
            "hc_quantile": HC_QUANTILE,
            "unweighted_inner_threshold": thresholds["ARCH_UNWEIGHTED"],
            "weighted_inner_threshold": thresholds["PCORRECT_WEIGHTED"],
            "outer_labels_used_for_model_selection": False,
            "outer_labels_used_for_threshold": False,
            "micro_threshold_search": False,
            "material_budget_used": MATERIAL_BUDGET,
            "inner_model": inner_model_audit,
            "outer_model": outer_model_audit,
        })
        print(
            f"[V227] {source_family} fold={outer_fold}/5 train={len(train)} "
            f"valid={len(valid)} pcorrect_supported={int(train.p_correct_supported.sum())}",
            flush=True,
        )
    evidence = pd.concat(predictions, ignore_index=True)
    for event_id, part in evidence.groupby("event_id"):
        require(set(part.candidate) == set(CANDIDATES) and len(part) == len(CANDIDATES),
                f"V227_CANDIDATE_ALIGNMENT:{event_id}")
    return evidence, fold_audits, pd.concat(pcorrect_rows, ignore_index=True), pcorrect_blocks


def safe_auc(y: Iterable[int], score: Iterable[float]) -> float | None:
    target = np.asarray(list(y), dtype=int)
    probability = np.asarray(list(score), dtype=float)
    return (
        float(roc_auc_score(target, probability))
        if len(target) and np.unique(target).size == 2 else None
    )


def safe_ba(y: Iterable[int], prediction: Iterable[bool]) -> float | None:
    target = np.asarray(list(y), dtype=int)
    value = np.asarray(list(prediction), dtype=bool)
    return (
        float(balanced_accuracy_score(target, value))
        if len(target) and np.unique(target).size == 2 else None
    )


def bootstrap_hc_net(frame: pd.DataFrame, seed: int) -> dict[str, Any]:
    work = frame.copy().reset_index(drop=True)
    work["day"] = pd.to_datetime(work.event_time_utc, utc=True).dt.date
    groups = {
        day: np.asarray(indices, dtype=int)
        for day, indices in work.groupby("day").indices.items()
    }
    days = np.asarray(sorted(groups), dtype=object)
    rng = np.random.default_rng(seed)
    values = []
    for _ in range(BOOTSTRAP_DRAWS):
        positions = np.concatenate([
            groups[day] for day in rng.choice(days, len(days), replace=True)
        ])
        sample = work.iloc[positions]
        selected = sample.high_conf.to_numpy(bool)
        if selected.any():
            values.append(float(sample.loc[selected, "signed_net"].mean()))
    require(values, "V227_EMPTY_BOOTSTRAP")
    return {
        "method": "event-day block bootstrap of frozen outer-OOF policy",
        "draws": len(values),
        "lower95": float(np.quantile(values, 0.025)),
        "median": float(np.median(values)),
        "upper95": float(np.quantile(values, 0.975)),
        "probability_gt_zero": float(np.mean(np.asarray(values) > 0.0)),
    }


def summarize(frame: pd.DataFrame, bootstrap_seed: int) -> dict[str, Any]:
    y = frame.y.to_numpy(int)
    probability = frame.prob_direction.to_numpy(float)
    prediction = frame.direction_prediction.to_numpy(bool)
    selected = frame.high_conf.to_numpy(bool)
    net = frame.loc[selected, "signed_net"].to_numpy(float)
    require(len(net) > 5, "V227_HC_SUPPORT_TOO_SMALL")
    ordered_net = np.sort(net)
    fold_metrics = []
    for fold, part in frame.groupby("outer_fold", sort=True):
        fold_metrics.append({
            "outer_fold": int(fold), "n": len(part),
            "auc": safe_auc(part.y, part.prob_direction),
            "balanced_accuracy": safe_ba(part.y, part.direction_prediction),
            "hc_n": int(part.high_conf.sum()),
            "hc_coverage": float(part.high_conf.mean()),
            "hc_accuracy": float(part.loc[part.high_conf, "direction_correct"].mean())
                if part.high_conf.any() else None,
            "hc_net": float(part.loc[part.high_conf, "signed_net"].mean())
                if part.high_conf.any() else None,
        })
    auc_values = [row["auc"] for row in fold_metrics if row["auc"] is not None]
    ba_values = [row["balanced_accuracy"] for row in fold_metrics
                 if row["balanced_accuracy"] is not None]
    return {
        "n": len(frame), "auc": safe_auc(y, probability),
        "balanced_accuracy": safe_ba(y, prediction),
        "accuracy": float((prediction == y.astype(bool)).mean()),
        "predicted_up_rate": float(prediction.mean()),
        "median_fold_auc": float(np.median(auc_values)),
        "worst_fold_auc": float(np.min(auc_values)),
        "median_fold_balanced_accuracy": float(np.median(ba_values)),
        "worst_fold_balanced_accuracy": float(np.min(ba_values)),
        "hc_n": int(selected.sum()), "hc_coverage": float(selected.mean()),
        "hc_accuracy": float(frame.loc[selected, "direction_correct"].mean()),
        "hc_balanced_accuracy": safe_ba(
            frame.loc[selected, "y"], frame.loc[selected, "direction_prediction"]
        ),
        "hc_net": float(net.mean()),
        "bootstrap_hc_net": bootstrap_hc_net(frame, bootstrap_seed),
        "hc_winsorized_1_99_net": float(
            np.clip(net, *np.quantile(net, [0.01, 0.99])).mean()
        ),
        "hc_top1_positive_removed_net": float(ordered_net[:-1].mean()),
        "hc_top5_positive_removed_net": float(ordered_net[:-5].mean()),
        "folds": fold_metrics,
    }


def metric_delta(left: dict[str, Any], right: dict[str, Any]) -> dict[str, float | None]:
    names = (
        "auc", "balanced_accuracy", "accuracy", "hc_coverage", "hc_accuracy",
        "hc_balanced_accuracy", "hc_net", "hc_winsorized_1_99_net",
        "hc_top5_positive_removed_net",
    )
    return {
        name: (
            float(left[name] - right[name])
            if left.get(name) is not None and right.get(name) is not None else None
        ) for name in names
    }


def build_report(
    evidence: pd.DataFrame,
    fold_audits: list[dict[str, Any]],
    pcorrect_evidence: pd.DataFrame,
    pcorrect_blocks: list[dict[str, Any]],
    authority: dict[str, Any],
    runtime: dict[str, Any],
) -> dict[str, Any]:
    metrics: dict[str, Any] = {}
    for scope in (*NEWS_SOURCES, "OVERALL"):
        part = evidence if scope == "OVERALL" else evidence[evidence.source_family.eq(scope)]
        metrics[scope] = {}
        for index, candidate in enumerate(CANDIDATES):
            candidate_part = part[part.candidate.eq(candidate)].copy()
            metrics[scope][candidate] = summarize(
                candidate_part, SEED + index * 100 + (0 if scope == "OVERALL" else NEWS_SOURCES.index(scope) + 1)
            )
        metrics[scope]["WEIGHTED_MINUS_UNWEIGHTED"] = metric_delta(
            metrics[scope]["PCORRECT_WEIGHTED"], metrics[scope]["ARCH_UNWEIGHTED"]
        )
        metrics[scope]["WEIGHTED_MINUS_V69_NOOP"] = metric_delta(
            metrics[scope]["PCORRECT_WEIGHTED"], metrics[scope]["V69_NOOP"]
        )
    require(not pcorrect_evidence.correctness_model_fit_contains_event.any(),
            "V227_REPORT_SAME_ROW_CORRECTNESS")
    supported = pcorrect_evidence.p_correct_supported.to_numpy(bool)
    supported_gaps = pd.to_numeric(
        pcorrect_evidence.loc[supported, "minimum_history_gap_minutes"], errors="coerce"
    )
    require((supported_gaps > 35.0).all(), "V227_REPORT_PCORRECT_GAP")
    require(all(int(row["text_cluster_overlap_n"]) == 0 for row in pcorrect_blocks),
            "V227_REPORT_PCORRECT_CLUSTER_OVERLAP")
    return {
        "version": 227,
        "hypothesis": "PAST_ONLY_PCORRECT_CONTINUOUS_DIRECTION_SAMPLE_WEIGHTING",
        "status": "OLD_DEV_DIAGNOSTIC_ONLY_NOT_INDEPENDENT_CONFIRMATION",
        "authority": authority, "runtime": runtime,
        "pre_registered_material_budget": {
            "budget_used": MATERIAL_BUDGET,
            "direction_architecture": "FULL_STRUCTURED_TEXT_L2_LOGISTIC_C_0.25_BALANCED",
            "pcorrect_architecture": "FULL_STRUCTURED_L2_LOGISTIC_C_0.25_BALANCED",
            "continuous_weight_transform": WEIGHT_TRANSFORM,
            "weight_range": [0.5, 1.5], "neutral_pcorrect": 0.5,
            "neutral_multiplier": 1.0,
            "hc_gate": "per-candidate fixed inner-past q80 absolute margin",
            "transform_search": False, "architecture_search": False,
            "micro_threshold_search": False, "outer_fold_selection": False,
        },
        "contract": {
            "outer_folds": 5, "outer_partition": "6 chronological blocks; first train-only",
            "source_specific": list(NEWS_SOURCES), "embargo_minutes": 35.0,
            "text_cluster_purge": True,
            "pcorrect_for_each_outer_train_row": "expanding block cross-fit from strictly earlier rows",
            "unsupported_pcorrect": 0.5,
            "same_row_correctness_allowed": False,
            "same_row_correctness_observed": False,
            "outer_labels_used_for_threshold_or_selection": False,
            "immutable_v69_noop": True,
            "identical_weighted_unweighted_architecture": True,
            "tplus2_content_provenance": "immutable contract; no independent ingest timestamp",
        },
        "inventory": {
            source: {
                "rows": int(evidence[
                    evidence.source_family.eq(source) & evidence.candidate.eq("V69_NOOP")
                ].shape[0]),
                "pcorrect_training_row_instances": int(
                    pcorrect_evidence.source_family.eq(source).sum()
                ),
                "pcorrect_supported_instances": int((
                    pcorrect_evidence.source_family.eq(source)
                    & pcorrect_evidence.p_correct_supported
                ).sum()),
                "pcorrect_neutral_instances": int((
                    pcorrect_evidence.source_family.eq(source)
                    & ~pcorrect_evidence.p_correct_supported
                ).sum()),
            } for source in NEWS_SOURCES
        },
        "metrics": metrics,
        "audit": {
            "outer_fold_audit_rows": len(fold_audits),
            "pcorrect_block_audit_rows": len(pcorrect_blocks),
            "pcorrect_training_row_instances": len(pcorrect_evidence),
            "same_row_correctness_reference_n": 0,
            "minimum_supported_history_gap_minutes": float(supported_gaps.min()),
            "pcorrect_text_cluster_overlap_n": int(sum(
                int(row["text_cluster_overlap_n"]) for row in pcorrect_blocks
            )),
            "outer_or_inner_labels_used_for_candidate_choice_n": 0,
        },
        "limitations": [
            "OLD_DEV_ONLY_NOT_INDEPENDENT_CONFIRMATION",
            "NO_CAPTURE_OR_INGEST_TIMESTAMP_FOR_TEXT",
            "V69_STRICT_OOF_FEATURE_AUTHORITY_IS_IMMUTABLE_NOT_REESTIMATED",
            "ONE_MATERIAL_WEIGHT_TRANSFORM_ONLY",
        ],
        "production_authorized": False,
        "research_seal_or_final_rows_read": False,
    }


def audit_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# V227 Strict Chronological News Direction Sample-Weighting",
        "",
        f"Status: `{report['status']}`",
        "",
        "One material budget was used. The continuous multiplier was fixed before the run as "
        "`0.5 + P_CORRECT_NEWS`; no transform, architecture, or threshold grid was searched.",
        "",
        "## Leakage contract",
        "",
        "- Every outer-train P_CORRECT_NEWS is neutral 0.5 or fitted only from rows strictly more than 35 minutes earlier.",
        "- Same-row correctness references and text-cluster overlap are zero.",
        "- Weighted and unweighted candidates share the exact feature matrix and model architecture.",
        "- High-confidence thresholds are fixed inner-past q80 margins; outer labels never select a threshold or candidate.",
        "- V69 probability, direction and high-confidence mask are copied as an immutable no-op baseline.",
        "",
        "## Results",
        "",
    ]
    for scope in (*NEWS_SOURCES, "OVERALL"):
        values = report["metrics"][scope]
        for candidate in CANDIDATES:
            row = values[candidate]
            lines.append(
                f"- {scope} / {candidate}: AUC={row['auc']:.6f}, BA={row['balanced_accuracy']:.6f}, "
                f"HC coverage={row['hc_coverage']:.6f}, HC accuracy={row['hc_accuracy']:.6f}, "
                f"HC net={row['hc_net']:.8f}, bootstrap lower95="
                f"{row['bootstrap_hc_net']['lower95']:.8f}."
            )
    lines.extend([
        "", "This is old-DEV diagnostic evidence only and is not an independent confirmation. "
        "No Research Seal or Final Meta rows were opened.", "",
    ])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cpu-ids", default="30,31")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    cpu_ids = tuple(int(piece.strip()) for piece in args.cpu_ids.split(",") if piece.strip())
    runtime = configure_runtime(cpu_ids)
    authority = verify_authority()
    news = load_news()
    # The lazy V225 import applies the repository runtime policy; confirm V227
    # restored its bounded environment and affinity afterward.
    runtime = configure_runtime(cpu_ids)
    all_evidence = []
    all_fold_audits = []
    all_pcorrect_rows = []
    all_pcorrect_blocks = []
    for source_family in NEWS_SOURCES:
        source = news[news.source_family.eq(source_family)].copy()
        evidence, fold_audits, p_rows, p_blocks = run_source(source)
        all_evidence.append(evidence)
        all_fold_audits.extend(fold_audits)
        all_pcorrect_rows.append(p_rows)
        all_pcorrect_blocks.extend(p_blocks)
    evidence = pd.concat(all_evidence, ignore_index=True)
    pcorrect_evidence = pd.concat(all_pcorrect_rows, ignore_index=True)
    report = build_report(
        evidence, all_fold_audits, pcorrect_evidence, all_pcorrect_blocks,
        authority, runtime,
    )
    OUT.mkdir(parents=True, exist_ok=True)
    atomic_csv_gz(evidence, OUT / "V227_DIRECTION_WEIGHTING_OOF.csv.gz")
    atomic_csv_gz(pcorrect_evidence, OUT / "V227_PCORRECT_TRAIN_CROSSFIT.csv.gz")
    fold_flat = []
    for row in all_fold_audits:
        flat = {key: value for key, value in row.items()
                if key not in {"inner_model", "outer_model"}}
        for prefix in ("inner_model", "outer_model"):
            flat.update({f"{prefix}__{key}": value for key, value in row[prefix].items()})
        fold_flat.append(flat)
    atomic_csv_gz(pd.DataFrame(fold_flat), OUT / "V227_OUTER_FOLD_AUDIT.csv.gz")
    atomic_csv_gz(pd.DataFrame(all_pcorrect_blocks), OUT / "V227_PCORRECT_BLOCK_AUDIT.csv.gz")
    atomic_json(report, OUT / "V227_DIRECTION_WEIGHTING_REPORT.json")
    markdown = OUT / "V227_DIRECTION_WEIGHTING_AUDIT.md"
    temporary = markdown.with_name(markdown.name + f".tmp.{os.getpid()}")
    temporary.write_text(audit_markdown(report), encoding="utf-8")
    temporary.replace(markdown)
    files = {
        path.name: {"sha256": sha256(path), "bytes": path.stat().st_size}
        for path in sorted(OUT.iterdir()) if path.is_file() and path.name != "MANIFEST.json"
    }
    tests = HERE / "V227_test_news_direction_sample_weighting.py"
    manifest = {
        "version": 227, "status": report["status"],
        "runner": {"path": str(Path(__file__).relative_to(ROOT)), "sha256": sha256(Path(__file__))},
        "tests": {
            "path": str(tests.relative_to(ROOT)), "sha256": sha256(tests),
        },
        "authorized_input_sha256": authority["sha256"], "files": files,
        "invariants": {
            "same_row_correctness_used": False,
            "outer_labels_used_for_selection_or_threshold": False,
            "immutable_v69_noop": True,
            "identical_weighted_unweighted_architecture": True,
            "research_seal_or_final_rows_read": False,
            "existing_v225_v226_registry_state_modified": False,
        },
    }
    atomic_json(manifest, OUT / "MANIFEST.json")
    print(json.dumps(json_clean({
        "status": report["status"], "metrics": report["metrics"],
        "audit": report["audit"], "manifest_sha256": sha256(OUT / "MANIFEST.json"),
        "files": files,
    }), ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
